// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IPoolManager} from "@uniswap/v4-core/src/interfaces/IPoolManager.sol";
import {IHooks} from "@uniswap/v4-core/src/interfaces/IHooks.sol";
import {PoolKey} from "@uniswap/v4-core/src/types/PoolKey.sol";
import {PoolId} from "@uniswap/v4-core/src/types/PoolId.sol";
import {Currency} from "@uniswap/v4-core/src/types/Currency.sol";
import {TickMath} from "@uniswap/v4-core/src/libraries/TickMath.sol";
import {IPositionManager} from "@uniswap/v4-periphery/src/interfaces/IPositionManager.sol";
import {IStateView} from "@uniswap/v4-periphery/src/interfaces/IStateView.sol";
import {IAllowanceTransfer} from "permit2/src/interfaces/IAllowanceTransfer.sol";
import {IERC721} from "@openzeppelin/contracts/token/ERC721/IERC721.sol";

import {UniswapV4Adapter} from "../../../src/adapters/UniswapV4Adapter.sol";
import {IAdapter} from "../../../src/interfaces/IAdapter.sol";
import {V4VaultHarness} from "../../mocks/v4/V4VaultHarness.sol";
import {V4SwapRouter} from "../../mocks/v4/V4SwapRouter.sol";

interface IPermit2Holder {
    function permit2() external view returns (address);
}

/// @notice Full position lifecycle of the Uniswap V4 adapter against a real hookless 0.05% pool on a pinned fork.
/// @dev Each chain's contract supplies the addresses from docs/INTEGRATIONS.md. Fees are generated by a third-party
///      trader swapping through a router built on `PoolManager.unlock`; every swap is bounded by a price limit so the
///      price path is the same whatever the pool's depth.
abstract contract UniswapV4AdapterForkBase is Test {
    int24 internal constant TICK_SPACING = 10;
    int24 internal constant HALF_RANGE = 200;
    int24 internal constant SWING = 40;

    IPoolManager internal poolManager;
    IPositionManager internal positionManager;
    IStateView internal stateView;
    IAllowanceTransfer internal permit2;
    address internal token0;
    address internal token1;
    PoolKey internal key;
    bytes32 internal poolId;
    bytes32 internal hookedId;

    V4VaultHarness internal vault;
    UniswapV4Adapter internal adapter;
    V4SwapRouter internal router;
    address internal trader = makeAddr("trader");
    address internal guardian = makeAddr("guardian");
    int24 internal center;

    uint256 internal last0;
    uint256 internal last1;

    function _fork() internal virtual;
    function _config()
        internal
        pure
        virtual
        returns (address pm, address posm, address sv, address weth, address stable, bytes32 expectedPoolId);
    function _fund(address token, address to, uint256 amount) internal virtual;
    function _amounts()
        internal
        pure
        virtual
        returns (uint256 weth, uint256 stable, uint256 traderWeth, uint256 traderStable);

    function setUp() public {
        _fork();
        (address pm, address posm, address sv, address weth, address stable, bytes32 expectedPoolId) = _config();
        poolManager = IPoolManager(pm);
        positionManager = IPositionManager(posm);
        stateView = IStateView(sv);
        permit2 = IAllowanceTransfer(IPermit2Holder(posm).permit2());
        (token0, token1) = weth < stable ? (weth, stable) : (stable, weth);

        key = PoolKey(Currency.wrap(token0), Currency.wrap(token1), 500, TICK_SPACING, IHooks(address(0)));
        poolId = PoolId.unwrap(key.toId());
        assertEq(poolId, expectedPoolId, "pool id differs from docs/INTEGRATIONS.md");
        PoolKey memory hooked = key;
        hooked.hooks = IHooks(address(0x4444000000000000000000000000000000000080));
        hookedId = PoolId.unwrap(hooked.toId());

        PoolKey[] memory keys = new PoolKey[](2);
        keys[0] = key;
        keys[1] = hooked;
        vault = new V4VaultHarness();
        adapter = new UniswapV4Adapter(address(vault), guardian, poolManager, positionManager, stateView, permit2, keys);
        vault.setAdapter(adapter);
        router = new V4SwapRouter(poolManager);

        (uint256 wethAmount, uint256 stableAmount, uint256 traderWeth, uint256 traderStable) = _amounts();
        _fund(weth, address(vault), wethAmount * 4);
        _fund(stable, address(vault), stableAmount * 4);
        _fund(weth, trader, traderWeth);
        _fund(stable, trader, traderStable);
        vm.startPrank(trader);
        IERC20(token0).approve(address(router), type(uint256).max);
        IERC20(token1).approve(address(router), type(uint256).max);
        vm.stopPrank();

        (, int24 tick,,) = stateView.getSlot0(PoolId.wrap(poolId));
        center = tick - (tick % TICK_SPACING);
    }

    /// DEC-079 (OPEN), OQ-12: a hooked pool is rejected even when listed.
    function test_DEC079_hookedPoolRejected() public {
        vm.expectRevert(abi.encodeWithSelector(IAdapter.UnknownPool.selector, hookedId));
        adapter.poolTokens(hookedId);
        (uint256 a0, uint256 a1) = _desired();
        vm.expectRevert(abi.encodeWithSelector(IAdapter.UnknownPool.selector, hookedId));
        vault.open(hookedId, token0, a0, token1, a1, _openParams(a0, a1));
        (address t0, address t1) = adapter.poolTokens(poolId);
        assertEq(t0, token0);
        assertEq(t1, token1);
    }

    /// DEC-079, Q60, DEC-080: open, earn, collect, increase, decrease, close; principal and income split to the wei,
    /// every amount lands in the vault, the adapter keeps nothing, cumulativeIncome never decreases.
    function test_DEC079_positionLifecycle() public {
        bytes32 positionKey = _stepOpen();
        _stepPriceAndIncome(positionKey);
        _stepCollect(positionKey);
        _swapToTick(center - SWING);
        _swapToTick(center);
        _stepIncrease(positionKey);
        _swapToTick(center + SWING);
        _swapToTick(center);
        _stepDecrease(positionKey);
        _swapToTick(center - SWING);
        _swapToTick(center + SWING / 2);
        _stepClose(positionKey);

        // After the close cumulativeIncome is exactly what was transferred to the vault as income.
        assertEq(adapter.cumulativeIncome(token0), adapter.realizedIncome(token0));
        assertEq(adapter.cumulativeIncome(token1), adapter.realizedIncome(token1));
        assertGt(adapter.realizedIncome(token0), 0);
        assertGt(adapter.realizedIncome(token1), 0);
    }

    /// Opens around the current tick from desired amounts; the vault pays exactly what the position took.
    function _stepOpen() internal returns (bytes32 positionKey) {
        (uint256 a0, uint256 a1) = _desired();
        uint256[2] memory before = _vaultBalances();
        uint256 used0;
        uint256 used1;
        (positionKey, used0, used1) = vault.open(poolId, token0, a0, token1, a1, _openParams(a0, a1));
        assertGt(used0, 0);
        assertGt(used1, 0);
        _assertVaultDelta(before, -int256(used0), -int256(used1));
        _assertAdapterHoldsNothing();
        IAdapter.PositionValue memory v = adapter.positionValue(positionKey);
        assertApproxEqAbs(v.principal0, used0, 1);
        assertApproxEqAbs(v.principal1, used1, 1);
        assertEq(v.income0 + v.income1, 0);
        _checkMonotonic();
    }

    /// Principal follows the price; each direction of trading produces income in its input token.
    function _stepPriceAndIncome(bytes32 positionKey) internal {
        IAdapter.PositionValue memory start = adapter.positionValue(positionKey);
        _swapToTick(center - SWING);
        IAdapter.PositionValue memory down = adapter.positionValue(positionKey);
        assertGt(down.principal0, start.principal0, "principal0 must grow when price falls");
        assertLt(down.principal1, start.principal1, "principal1 must shrink when price falls");
        assertGt(down.income0, 0, "token0 income after token0 sales");
        _checkMonotonic();

        _swapToTick(center + SWING);
        IAdapter.PositionValue memory up = adapter.positionValue(positionKey);
        assertGt(up.income1, 0, "token1 income after token1 sales");
        assertGe(up.income0, down.income0);
        assertLt(up.principal0, down.principal0);
        assertGt(up.principal1, down.principal1);
        _checkMonotonic();
    }

    /// Collect takes exactly the uncollected income; realization leaves cumulativeIncome unchanged.
    function _stepCollect(bytes32 positionKey) internal {
        IAdapter.PositionValue memory v = adapter.positionValue(positionKey);
        uint256 cumulative0 = adapter.cumulativeIncome(token0);
        uint256 cumulative1 = adapter.cumulativeIncome(token1);
        uint256[2] memory before = _vaultBalances();
        IAdapter.Amounts memory a = vault.collect(positionKey);
        assertEq(a.income0, v.income0);
        assertEq(a.income1, v.income1);
        assertEq(a.principal0 + a.principal1, 0);
        _assertVaultDelta(before, int256(a.income0), int256(a.income1));
        assertEq(adapter.cumulativeIncome(token0), cumulative0);
        assertEq(adapter.cumulativeIncome(token1), cumulative1);
        IAdapter.PositionValue memory afterCollect = adapter.positionValue(positionKey);
        assertEq(afterCollect.income0 + afterCollect.income1, 0);
        assertEq(afterCollect.principal0, v.principal0);
        assertEq(afterCollect.principal1, v.principal1);
        _assertAdapterHoldsNothing();
        _checkMonotonic();
    }

    /// Increase: income realized by the increase is reported apart from the principal paid in.
    function _stepIncrease(bytes32 positionKey) internal {
        (uint256 a0, uint256 a1) = _desired();
        IAdapter.PositionValue memory v = adapter.positionValue(positionKey);
        bytes memory params = _increaseParams(v.liquidity / 2, a0, a1);
        uint256[2] memory before = _vaultBalances();
        // r = (used0, used1, income0, income1)
        uint256[4] memory r;
        (r[0], r[1], r[2], r[3]) = vault.increase(positionKey, token0, a0, token1, a1, params);
        assertEq(r[2], v.income0);
        assertEq(r[3], v.income1);
        assertGt(r[2] + r[3], 0);
        _assertVaultDelta(before, int256(r[2]) - int256(r[0]), int256(r[3]) - int256(r[1]));
        assertEq(adapter.positionValue(positionKey).liquidity, v.liquidity + v.liquidity / 2);
        _assertAdapterHoldsNothing();
        _checkMonotonic();
    }

    /// Decrease a third: DECREASE of 0 realizes the income, then the principal is removed.
    function _stepDecrease(bytes32 positionKey) internal {
        IAdapter.PositionValue memory v = adapter.positionValue(positionKey);
        uint256[2] memory before = _vaultBalances();
        IAdapter.Amounts memory a = vault.decrease(positionKey, _decreaseParams(v.liquidity / 3));
        assertEq(a.income0, v.income0);
        assertEq(a.income1, v.income1);
        assertApproxEqRel(a.principal0, v.principal0 / 3, 1e12);
        assertApproxEqRel(a.principal1, v.principal1 / 3, 1e12);
        _assertVaultDelta(before, int256(a.principal0 + a.income0), int256(a.principal1 + a.income1));
        _assertAdapterHoldsNothing();
        _checkMonotonic();
    }

    /// Close: the whole principal and the income, split to the wei; the key is gone.
    function _stepClose(bytes32 positionKey) internal {
        IAdapter.PositionValue memory v = adapter.positionValue(positionKey);
        uint256[2] memory before = _vaultBalances();
        IAdapter.Amounts memory a = vault.close(positionKey, _closeParams());
        assertEq(a.principal0, v.principal0);
        assertEq(a.principal1, v.principal1);
        assertEq(a.income0, v.income0);
        assertEq(a.income1, v.income1);
        _assertVaultDelta(before, int256(a.principal0 + a.income0), int256(a.principal1 + a.income1));
        assertEq(adapter.positionKeys().length, 0);
        vm.expectRevert(abi.encodeWithSelector(IAdapter.UnknownPosition.selector, positionKey));
        adapter.positionValue(positionKey);
        _assertAdapterHoldsNothing();
        _checkMonotonic();
    }

    /// DEC-079, IAdapter custody: the position NFT belongs to the adapter while open and is burned by the close, so
    /// nothing of the position survives in the PositionManager (no stuck NFT, no residual liquidity or fee growth).
    function test_DEC079_closeBurnsThePositionNft() public {
        bytes32 positionKey = _stepOpen();
        uint256 tokenId = uint256(positionKey);
        assertEq(IERC721(address(positionManager)).ownerOf(tokenId), address(adapter), "adapter owns the NFT");
        _swapToTick(center - SWING);
        _swapToTick(center);
        _stepClose(positionKey);
        vm.expectRevert();
        IERC721(address(positionManager)).ownerOf(tokenId);
        (uint128 liquidity, uint256 last0, uint256 last1) = stateView.getPositionInfo(
            PoolId.wrap(poolId), address(positionManager), center - HALF_RANGE, center + HALF_RANGE, positionKey
        );
        assertEq(liquidity, 0, "no liquidity left in the PoolManager");
        // Fee growth checkpoints stay on the cleared position slot; they carry no value without liquidity.
        last0;
        last1;
    }

    // ------------------------------------------------------------------ helpers

    function _desired() internal pure returns (uint256 amount0, uint256 amount1) {
        (uint256 weth, uint256 stable,,) = _amounts();
        // WETH sorts below both USDC (Arbitrum) and USDG (Robinhood).
        return (weth, stable);
    }

    function _swapToTick(int24 targetTick) internal {
        (, int24 tick,,) = stateView.getSlot0(PoolId.wrap(poolId));
        if (tick == targetTick) return;
        bool zeroForOne = targetTick < tick;
        vm.prank(trader);
        router.swap(key, zeroForOne, -int256(uint256(type(uint128).max)), TickMath.getSqrtPriceAtTick(targetTick));
        (, tick,,) = stateView.getSlot0(PoolId.wrap(poolId));
        assertApproxEqAbs(int256(tick), int256(targetTick), 1, "swap did not reach the target tick");
    }

    function _checkMonotonic() internal {
        uint256 now0 = adapter.cumulativeIncome(token0);
        uint256 now1 = adapter.cumulativeIncome(token1);
        assertGe(now0, last0, "cumulativeIncome token0 decreased");
        assertGe(now1, last1, "cumulativeIncome token1 decreased");
        (last0, last1) = (now0, now1);
    }

    function _vaultBalances() internal view returns (uint256[2] memory b) {
        b[0] = IERC20(token0).balanceOf(address(vault));
        b[1] = IERC20(token1).balanceOf(address(vault));
    }

    function _assertVaultDelta(uint256[2] memory before, int256 delta0, int256 delta1) internal view {
        assertEq(int256(IERC20(token0).balanceOf(address(vault))) - int256(before[0]), delta0, "vault token0 delta");
        assertEq(int256(IERC20(token1).balanceOf(address(vault))) - int256(before[1]), delta1, "vault token1 delta");
    }

    function _assertAdapterHoldsNothing() internal view {
        assertEq(IERC20(token0).balanceOf(address(adapter)), 0, "adapter token0 balance");
        assertEq(IERC20(token1).balanceOf(address(adapter)), 0, "adapter token1 balance");
        assertEq(IERC20(token0).allowance(address(adapter), address(permit2)), 0);
        assertEq(IERC20(token1).allowance(address(adapter), address(permit2)), 0);
        (uint160 p0,,) = permit2.allowance(address(adapter), token0, address(positionManager));
        (uint160 p1,,) = permit2.allowance(address(adapter), token1, address(positionManager));
        assertEq(p0, 0);
        assertEq(p1, 0);
    }

    function _openParams(uint256 a0, uint256 a1) internal view returns (bytes memory) {
        return abi.encode(
            UniswapV4Adapter.OpenParams({
                tickLower: center - HALF_RANGE,
                tickUpper: center + HALF_RANGE,
                liquidity: 0,
                amount0Max: uint128(a0),
                amount1Max: uint128(a1),
                amount0Min: 0,
                amount1Min: 0,
                deadline: block.timestamp
            })
        );
    }

    function _increaseParams(uint128 liquidity, uint256 a0, uint256 a1) internal view returns (bytes memory) {
        return abi.encode(
            UniswapV4Adapter.IncreaseParams({
                liquidity: liquidity,
                amount0Max: uint128(a0),
                amount1Max: uint128(a1),
                amount0Min: 0,
                amount1Min: 0,
                deadline: block.timestamp
            })
        );
    }

    function _decreaseParams(uint128 liquidity) internal view returns (bytes memory) {
        return abi.encode(
            UniswapV4Adapter.DecreaseParams({
                liquidity: liquidity, amount0Min: 0, amount1Min: 0, deadline: block.timestamp
            })
        );
    }

    function _closeParams() internal view returns (bytes memory) {
        return abi.encode(UniswapV4Adapter.CloseParams({amount0Min: 0, amount1Min: 0, deadline: block.timestamp}));
    }
}

/// @notice Arbitrum One (Hub Chain): WETH/USDC 0.05%, tick spacing 10, no hooks.
contract UniswapV4AdapterArbitrumForkTest is UniswapV4AdapterForkBase {
    function _fork() internal override {
        vm.createSelectFork(vm.envString("ARBITRUM_RPC_URL"), vm.envUint("ARBITRUM_FORK_BLOCK"));
    }

    function _config() internal pure override returns (address, address, address, address, address, bytes32) {
        return (
            0x360E68faCcca8cA495c1B759Fd9EEe466db9FB32,
            0xd88F38F930b7952f2DB2432Cb002E7abbF3dD869,
            0x76Fd297e2D437cd7f76d50F01AfE6160f86e9990,
            0x82aF49447D8a07e3bd95BD0d56f35241523fBab1,
            0xaf88d065e77c8cC2239327C5EDb3A432268e5831,
            0xfc7b3ad139daaf1e9c3637ed921c154d1b04286f8a82b805a6c352da57028653
        );
    }

    function _amounts() internal pure override returns (uint256, uint256, uint256, uint256) {
        return (10e18, 40_000e6, 50_000e18, 200_000_000e6);
    }

    function _fund(address token, address to, uint256 amount) internal override {
        deal(token, to, amount);
    }
}

/// @notice Robinhood Chain (Spoke Chain): WETH/USDG 0.05%, tick spacing 10, no hooks.
contract UniswapV4AdapterRobinhoodForkTest is UniswapV4AdapterForkBase {
    function _fork() internal override {
        vm.createSelectFork(vm.envString("ROBINHOOD_RPC_URL"), vm.envUint("ROBINHOOD_FORK_BLOCK"));
    }

    function _config() internal pure override returns (address, address, address, address, address, bytes32) {
        return (
            0x8366a39CC670B4001A1121B8F6A443A643e40951,
            0x58daec3116aae6D93017bAAea7749052E8a04fA7,
            0xF3334192D15450CdD385c8B70e03f9A6bD9E673b,
            0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73,
            0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168,
            0xfcfae8fa0bd6da961bcf5d990f27690932deac4f093e99bf3e871691c6586593
        );
    }

    function _amounts() internal pure override returns (uint256, uint256, uint256, uint256) {
        return (1e18, 4000e6, 10_000e18, 50_000_000e6);
    }

    function _fund(address token, address to, uint256 amount) internal override {
        deal(token, to, amount);
    }
}
